version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres:14.1-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
       - .docker:/data/postgres
    ports:
      - "5432:5432"
volumes:
    postgres: